highlighter: "rouge"
# - markdown: "kramdown"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

plugins:
  - jekyll-sitemap

title: "David Owens"
tagline: ""
description: "Follow <a href=\"https://micro.blog/owensd\">@owensd on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/owensd\">@owensd on Micro.blog</a>."
baseurl: ""
url: "http://thoughts.owensd.io"
markdown: "kramdown"
username: "owensd"
microblog_user: "owensd"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "David Owens"
name: "David Owens"
gravatar_hash: "012bc4c5e7b0c2829fff88611143c108"
avatar: "https://micro.blog/owensd/avatar.jpg"
full_name: "David Owens"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Pacific-New"
site_id: "5509"
gems: ["jekyll-paginate"]
itunes_description: ""
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "David Owens"
itunes_email: ""
podcast: false